# Sets
- a collection of objects and denoted by {}
- For example, 𝑆=𝑜𝑟𝑎𝑛𝑔𝑒,𝑎𝑝𝑝𝑙𝑒,𝑏𝑎𝑛𝑎𝑛𝑎 means “S is the set containing ‘orange’, ‘apple’, and ‘banana’”.
- Given two sets, 𝐴 and 𝐵, the union of 𝐴 and 𝐵 is denoted by 𝐴∪𝐵 and equal to the set containing all the elements of 𝐴 and 𝐵. 
- The intersect of 𝐴 and 𝐵 is denoted by 𝐴∩𝐵 and equal to the set containing all the elements that belong to both 𝐴 and 𝐵. 
- In set notation, a colon, :, is used to mean “such that”. 
- The symbol ∈ is used to denote that an object is contained in a set. For example 𝑎∈𝐴 means “𝑎 is a member of 𝐴” or “𝑎 is in 𝐴.” 
- A backslash, ∖, in set notation means set minus. So if 𝑎∈𝐴 then 𝐴∖𝑎 means “𝐴 minus the element, 𝑎.”

TRY IT! Let 𝑆 be the set of all real (𝑥,𝑦) pairs such that 𝑥2+𝑦2=1. Write 𝑆 using set notation.

𝑆={(𝑥,𝑦):𝑥,𝑦∈ℝ,𝑥2+𝑦2=1}

Vector - an object that has both magnitude and direction

A vector in ℝ𝑛 is an 𝑛-tuple, or point, in ℝ𝑛. Vectors can be written horizontally (i.e., with the elements of the vector next to each other) in a row vector, or vertically (i.e., with the elements of the vector on top of each other) in a column vector.

 The transpose of a column vector is a row vector of the same length, and the transpose of a row vector is a column vector. In mathematics, the transpose is denoted by a superscript 𝑇, or 𝑣𝑇.

Zero vector is the vector in ℝ𝑛 containing all zeros

The norm of a vector is a measure of its length. There are many ways of defining the length of a vector depending on the metric used (i.e., the distance formula chosen). 
1.  𝐿2 norm, which is computed according to the distance formula you are probably familiar with from grade school. The 𝐿2 norm of a vector 𝑣 is denoted by ‖𝑣‖2 and ‖𝑣‖2=∑𝑖𝑣2𝑖‾‾‾‾‾‾√. This is sometimes also called Euclidian length and refers to the “physical” length of a vector in one-, two-, or three-dimensional space. The 𝐿1 norm, or “Manhattan Distance,” is computed as ‖𝑣‖1=∑𝑖|𝑣𝑖|, and is named after the grid-like road structure in New York City. In general, the p-norm, 𝐿𝑝, of a vector is ‖𝑣‖𝑝=(∑𝑖𝑣𝑝𝑖)‾‾‾‾‾‾‾√𝑝. The 𝐿∞ norm is the 𝑝-norm, where 𝑝=∞. The 𝐿∞ norm is written as ||𝑣||∞ and it is equal to the maximum absolute value in 𝑣.

In [2]:
# create a row vector and column vector and show the shape of the vectors
import numpy as np
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(vector_row.shape)
print(vector_column.shape)

(1, 5)
(4, 1)


Note! In Python, the row vector and column vector are a little bit tricky. You can see from the above in order to get the 1 row and 4 columns or 4 rows and 1 column vectors, we have to use list of list to specify it. You can define np.array([1,2,3,4]), but you will soon notice that it doesn’t contain information about row or column.

In [3]:
# TRY IT! Transpose the row vector we defined above into a column vector and calculate the 𝐿1, 𝐿2, and 𝐿∞ norm of it. 
# Verify that the 𝐿∞ norm of a vector is equivalent to the maximum value of the elements in the vector.

from numpy.linalg import norm
new_vector = vector_row.T
print(new_vector)


norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf)
print('L_1 is: %.1f'%norm_1)
print('L_2 is: %.1f'%norm_2)
print('L_inf is: %.1f'%norm_inf)

[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L_1 is: 15.0
L_2 is: 7.4
L_inf is: 5.0


Vector addition 

## Dot Product
the dot product of two vectors is the sum of the product of the respective elements in each vector

The angle between two vectors, 𝜃, is defined by the formula:
𝑣⋅𝑤=‖𝑣‖2‖𝑤‖2cos𝜃

In [4]:
#dot product
a = np.array([4,5,6])
b = np.array([7,4,2])
print(np.dot(a,b))

60


In [5]:
# another way to write teh dot product
a = np.array([4,5,6])
b = np.array([7,4,2])
print(a @ b)

60


In [6]:
#https://www.learndatasci.com/glossary/orthogonal-and-orthonormal-vectors/
v1 = np.array([1,-2, 4])
v2 = np.array([2, 5, 2])

dot_product = np.sum(v1*v2)
print("The dot product of v1 and v2 is", dot_product )

The dot product of v1 and v2 is 0


In [7]:
# another way of using the dot product to find orthogonality between two vectors
v1 = np.array([1,-2, 4])
v2 = np.array([2, 5, 2])

transposeofv1 = np.transpose(v1)
result = np.dot(v2, transposeofv1)
print(result)

0


In [4]:
# compute the angles between the vectors v = [10,9,3] and w = [2, 5, 12]
# refer to khan academy video
from numpy import arccos, dot

v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
theta = \
    arccos(dot(v, w.T)/(norm(v)*norm(w))) 
# transpose vector w b/c you need a number/scalar. if you don't transpose, you'll get a matrix; dot product requires
# a number
print(theta)

[[0.97992471]]


In [11]:
from numpy import arccos, dot

v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
theta = \
    arccos(dot(v, w.T)/(norm(v)*norm(w))) 
# transpose vector w b/c you need a number/scalar. if you don't transpose, you'll get a matrix; dot product requires
# a number
print(theta)

[[0.97992471]]


In [6]:
# compute the angle between the vectors

v= np.array([[2,2,-1]])
v2 = np.array([[5,-3,2]])
theta = \
    arccos(dot(v, v2.T)/(norm(v)*norm(v2)))
print(theta)
#1.46 radians which is about 84 degrees

[[1.46243678]]


In [7]:
v = np.array([[4, 2, 5]])
v1 = np.array([[-1, 3, -6]])
v2 = np.array([[7, -5, 1]])
# find a dot b:
theta = \
    arccos(dot(v, v1.T)/(norm(v)*norm(v1)))
print(theta)
# find b dot c
theta = \
    arccos(dot(v1, v2.T)/ (norm(v1)*norm(v2)))
print(theta)

[[2.23371729]]
[[2.06769738]]


## Cross Product
multiples two vectors to get another vector

it's a  vector perpendicular to to both vector v and vector w with the length equal to the area enclosed by the parallelogram created by the two vectors

The cross product between two vectors, 𝑣 and 𝑤, is written 𝑣×𝑤. It is defined by 𝑣×𝑤=‖𝑣‖2‖𝑤‖2sin(𝜃)n, where 𝜃 is the angle between the 𝑣 and 𝑤 (which can be computed from the dot product) and 𝑛 is a vector perpendicular to both 𝑣 and 𝑤 with unit length (i.e., the length is one). The geometric interpretation of the cross product is a vector perpendicular to both 𝑣 and 𝑤 with length equal to the area enclosed by the parallelogram created by the two vectors.


In [18]:
# TRY IT! Given the vectors 𝑣=[0,2,0] and 𝑤=[3,0,0], use the Numpy function cross to compute the cross product of v and w.

v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])
print(np.cross(v, w))

[[ 0  0 -6]]


## Linear Combination
Assuming that 𝑆 is a set in which addition and scalar multiplication are defined, a linear combination of 𝑆 is defined as $ ∑𝛼𝑖𝑠𝑖 $

where 𝛼𝑖 is any real number and 𝑠𝑖 is the 𝑖th object in 𝑆. Sometimes the 𝛼𝑖 values are called the coefficients of 𝑠𝑖. Linear combinations can be used to describe numerous things. For example, a grocery bill can be written ∑𝑐𝑖𝑛𝑖, where 𝑐𝑖 is the cost of item 𝑖 and 𝑛𝑖 is the number of item 𝑖 purchased. Thus, the total cost is a linear combination of the items purchased.

# linearly independent
- a set is linearly independent if no object in the set can be written as a linear combination of other objects in the set
- A set of vectors that is not linearly independent is linearly dependent.

In [4]:
# TRY IT! Given the row vectors 𝑣=[0,3,2], 𝑤=[4,1,1], and 𝑢=[0,−2,0], write the vector 𝑥=[−8,−1,4] as a linear combination of 𝑣, 𝑤, and 𝑢.
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])
x = 3*v-2*w+4*u
print(x)

[[-8 -1  4]]


In [5]:
# creating a matrix
#create matrix A
# best way to create a matrix is to use numpy array and specify the arrays inside the brackets. 3 rows = 3 square brackets

A = np.array([[1,2,4], [2,4,3], [0,1,1]])
A

array([[1, 2, 4],
       [2, 4, 3],
       [0, 1, 1]])

In [19]:
# transpose matrix A and  save as A_T
A_T =  A.transpose()
A_T

array([[1, 2, 0],
       [2, 4, 1],
       [4, 3, 1]])

In [9]:
# generate a matrix. Use the arange function to create a one dimensional matrix and you can reshape it to create 2D matrix or more
B = np.arange(1,10) # 10 is not inclusive
print(B) # prints an array of numbers

B.reshape(3,3) # gives a 3x3 matrix with the numbers generated

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# generate an array of even numbers for the matrix
B = np.arange(0,11,2)
print(B) # prints an array of numbers
B.reshape(2,3)

[ 0  2  4  6  8 10]


array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [22]:
# transpose matrix B and save as B_T
B = np.array([[2,-1],[3,2]])
B
B_T = B.transpose()
B_T

array([[ 2,  3],
       [-1,  2]])

In [15]:
#transpose a matrix
D  = np.array([[3,4,2], [1,5,4]])
#check the matrix
D

array([[3, 4, 2],
       [1, 5, 4]])

In [18]:
#transpose the matrix with only two columns
D.transpose()

array([[3, 1],
       [4, 5],
       [2, 4]])

## Matrix Multiplication

In [23]:
# create a matrix
A1 = np.arange(1,10).reshape(3,3)
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
A2 = np.arange(5,14).reshape(3,3)
A2

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [28]:
#this is element wise multiplication
# 1*5, 2*6, 3*7, etc.
A3 = A1 *A2
A3

array([[  5,  12,  21],
       [ 32,  45,  60],
       [ 77,  96, 117]])

In [29]:
#  Real matrix multiplication multiplies the first row in the first matrix by the first column in the second matrix
# Matrix multiplication using dot()
A4 = A1.dot(A2)
A4

array([[ 54,  60,  66],
       [126, 141, 156],
       [198, 222, 246]])

In [10]:
# Verifying the result above
a = ((1*5)+(2*8)+(3*11))
a
b = ((4*6)+(5*9)+(6*12))
b
c = (7*7)+(8*10)+(9*13)
c

246

In [21]:
from numpy.linalg import inv
M = np.array([[0,2,1,3], 
             [3,2,8,1], 
             [1,0,0,3],
             [0,3,2,1]])

M

array([[0, 2, 1, 3],
       [3, 2, 8, 1],
       [1, 0, 0, 3],
       [0, 3, 2, 1]])