#  Vectors 

In [2]:
import numpy as np
v = np.array([[1], [2], [3]])
v2 = np.array([[-1], [-2], [-3]])
print(v)

[[1]
 [2]
 [3]]


In [3]:
print(v.T) # transpose

[[1 2 3]]


In [4]:
v.shape

(3, 1)

# Matrices

In [5]:
M = np.array([[1,2,3],[4,5,6], [7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
M.shape

(3, 3)

In [7]:
#Scalar
x=3.5

#zipping
new_matrix = list(zip(v,v2))
new_matrix

#output shows the location in memory...similar to classes

[(array([1]), array([-1])),
 (array([2]), array([-2])),
 (array([3]), array([-3]))]

In [8]:
type(new_matrix)

list

In [9]:
#dot product of a and b = ax*bx + ay*by

# dot product

We use the dot product to multiply vectors. With 2D vectors, this is the  same as matrix multiplication, and we produce a scalar value (a number, not a vector).

Result tells you the degree to which the vectors interact, or the interaction between similar dimensions.

Why do we care? rendering, force diagrams, solar panel tracking

In [10]:
print(v.T)
print(v)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [11]:
#1*1 + 2*2 + 3*3
np.dot(v.T,v)

array([[14]])

In [12]:
# use directionality(north, south, east, west) and convert that into vectors
#directionality example
north = np.array([0,1])
east = np.array([1,0])
south = np.array([0,-1])
west= np.array([-1,0])

#to what degree are the two directions the same
np.dot(north, south)
#what directions have nothing in common
np.dot(north, east)

0

In [13]:
#to what degree are north and south the same?
#create an example
np.dot(north, south)

# 1 refers to them having the same x-axis and have 1 degree in common. This is the degree of similarity

-1

# Cross product 
- think of the ceiling and it being on the wall. The vector is the two corners

Type of vector multiplicaton, bit it shows the interaction between different components of the vector. 
It tracks all the cross interaction between dimensions

When you compute the cross product, you get a new vector that is perpendicular to both the input vectors

In each part of the corss product calculation, you are leaving out an interaction. * this could be stated better

Why do we care?
Torque and the moment of force
moment = measure of tendency to rotate about a particular point

In [14]:
np.cross(v,v2, axisa=0, axisb=0)

#outcome is all zeroes because the values are the opposite of each other

array([[0, 0, 0]])

# Orthogonality  

Two vectors are orthoganal if they're perpendicular to eachother
The dot product is 0 or the identity matrix

Below is latex documentation

$$ A \cdot A^T = I $$


In [15]:
# this is an identity matrix
# a test for orthogonality is if the matrix and its transpose equal the identity matrix
M = np.array([[1,0,0],
            [0,1,0],
            [0,0,1]])
M

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [16]:
np.dot(M, M.T)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [17]:
# this is not orthogonal since the diagnal isn't 1
#doesnt produce an identity matrix, and therefore is not orthogonal
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.dot(M,M.T)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

Shift+tab in an open paranthesis gives you the info about a function